### ISSUE TITLE
PDF Coming Out Blank

### ISSUE THREAD

**Issue by Karacraft** [PHPJasper/phpjasper#138]
@geekcom @jadsonbr
Hi,I am able to process the `simple.jrxml` (Created in JasperStudio) and output comes out as `simple.pdf & simple.rtf`
However, instead of showing data, it shows "**Null**" values only.

I've tried the `output()` option and copied the following information

`jasperstarter process "C:\Dev\server\data\htdocs\gen-inventory\public/reports/simple.jrxml" -o "C:\Dev\server\data\htdocs\gen-inventory\public/reports/1552841084_simple" -f pdf rtf -t mysql -u root -p lockdb+ -H localhost -n general_inventory --db-port 3306`

And the output in terminal shows;

`Sun Mar 17 21:47:42 PKT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26L 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with ions not using SSexisting applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setrue and providetting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.Unable to connect to database: Could not create connection to database server.`

I've tried to search and stop this **useSSL** but unable to get information to set it up. Please help in this regard. If possible, a guidance to setup database connection properly to mysql server.

**Desktop (please complete the following information):**
 - OS: [Windows 10 1803]
 - Browser [Firefox]
 - Version [65]
- Laravel [5.8]
![jasper](https://user-images.githubusercontent.com/42495441/54494679-beb5f680-48fe-11e9-8a1d-ff85c5e304cd.jpg)

**Comment by geekcom** [comment]
Hi @Karacraft this bug was solved in [last version](https://github.com/PHPJasper/phpjasper/releases/tag/3.0.0), please update your version just run `composer update`

**Comment by geekcom** [comment]
better use 3.0 above version of PHPJasper, please read the docs.

**Comment by Karacraft** [comment]
Thanks for the Update @geekcom 
Problem remains.

**PhpJaspser Process - Without DB Options -- PDF is still showing null**
```
Route::get('report', function () {

    $input = public_path() . '/reports/simple.jrxml';
    $output = public_path() . '/reports/'.time().'_simple';

    $options = [
        'format' => ['pdf', 'rtf'],
    ];
    
    $report = new PHPJasper;
    $report->process(
        $input,
        $output,
        $options
    )->execute();
  
    return 'Report is Made';
});
```
Output (this creates a pdf file in terminal as well with jasperstarter.exe)
```
jasperstarter process "C:\Dev\server\data\htdocs\gen-inventory\public/reports/simple.jrxml" -o "C:\Dev\server\data\htdocs\gen-inventory\public/reports/1552884204_simple" -f pdf rtf
```

**PhpJaspser Process - With DB Options**

```
Route::get('report', function () {

    $input = public_path() . '/reports/simple.jrxml';
    $output = public_path() . '/reports/'.time().'_simple';

    $options = [
        'format' => ['pdf', 'rtf'],
        'db_connection' => [
            'driver' => 'mysql',
            'username' => 'root',
            'password' => 'lockdb+',
            'host' => '127.0.0.1',
            'database' => 'general_inventory',
            'port' => '3306'
        ]
    ];
    
    $report = new PHPJasper;
    $report->process(
        $input,
        $output,
        $options
    )->execute();
    return 'Report is Made';
});
```

Output
```
jasperstarter process "C:\Dev\server\data\htdocs\gen-inventory\public/reports/simple.jrxml" -o "C:\Dev\server\data\htdocs\gen-inventory\public/reports/1552884262_simple" -f pdf rtf -t mysql -u root -p lockdb+ -H 127.0.0.1 -n general_inventory --db-port 3306
```
This raises error in laravel (```Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.```) as well as in terminal (```Unable to connect to database: Could not create connection to database server.```)

**Comment by geekcom** [comment]
Please check connection options.

**Comment by Karacraft** [comment]
Ok. so, i worked with the connection after your reply, and after 2 and half hours, i was finally able to get the data as i desired. The problem was **jdb_dir** 
So i removed it and the report is working 💯  fine.

Reference for Others;
```
$jdbc_driver = 'com.mysql.jdbc.Driver';
$jdbc_url = 'jdbc:mysql://127.0.0.1:3306/general_inventory';
$options = [
        'format' => ['pdf', 'rtf'],
        'db_connection' => [
            'driver' => 'mysql',
            'username' => 'root',
            'password' => 'lockdb+',
            'host' => '127.0.0.1',
            'database' => 'general_inventory',
            'port' => '3306',
            'jdbc_driver' => $jdbc_driver,
            'jdbc_url' => $jdbc_url
            // 'jdbc_dir' => $jdbc_dir  -- DONT USE THIS
        ]
```
Also, in documents *__DIR__* is being used, which results in **yourdirectory/routes** instead of **yourdirectory** so please use **base_path()** before your reports.

**ADDENDUM**
Users can use the following code to wait for the large pdf creation and then show it in broswer;
```
while (!file_exists(public_path() . '/reports/' . $filename . '.pdf')) sleep(1);
return response()->file(public_path() . '/reports/' . $filename . '.pdf');
```
@geekcom  Please mark this issue solved and if possible, add my findings in Laravel section for Version 5.8. 
Thanks 👍
